### ISSUE TITLE
Like to customize gabriel...

### ISSUE THREAD

**Issue by sowjet** [thiscouldbejd/Gabriel#10]
I think Gabriel is a really useful tool and I like to customize it.
Only thing missing are skills in setting up an add on.

Could you give some good starting points to learn how to put the code available from the repository in a working google docs add on?

**Comment by sowjet** [comment]
I think I allready know it now :D.

Starting point should be the google docs scripteditor!

thx anyway

**Comment by thiscouldbejd** [comment]
Ok! Let me know if you need anything :)
