### ISSUE TITLE
Strikethough Syntax

### ISSUE THREAD

**Issue by Jayp0weru5r** [thiscouldbejd/Gabriel#11]
When using a google doc and assigning font as strikethrough this is not created correctly. 

```
Strikethrough uses two tildes. ~~Scratch this.~~
```

Thanks I really have been enjoying this add in.

**Comment by thiscouldbejd** [comment]
Hi - will look at this for you shortly!

Jd

**Comment by Jayp0weru5r** [comment]
I don't really use it, but was just testing all the possibilities and noticed it wasn't working.

**Comment by thiscouldbejd** [comment]
Hi,

Thanks for the report & feedback - I've popped some extra code in the Markdown.gs file to check for strikethrough text and output appropriately. As 'strikethough' is not part of the 'original' Markdown syntax, I am thinking of fully going over to Github-Flavoured Markdown (as that's where all the stuff ends up!), which means a few more changes to bring the parser in line with all it's features / idiosyncrasies. The code base (on this repo) is now up to date, but I've been working on a few other changes (YAML property setting in the Add-On) so will await completion of that version before pushing it live to the Add-On store.

Yours,

JD
