### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by PaulLaux** [thiscouldbejd/Gabriel#5]
When writing in other languages text renders as bunch of question marks.
Any plans to fix this soon?

**Comment by fgweekly** [comment]
I would love to see this fixed too. ^^

**Comment by thiscouldbejd** [comment]
Tracked down the issue to: Utilities.base64Encode - am looking at what can be done to deal with this now! Sorry for the delay, completely missed this issue when it was opened....

**Comment by thiscouldbejd** [comment]
Yep - ridiculously simple fix, slight 'undocumented' feature of Utilities.base64Encode (https://developers.google.com/apps-script/reference/utilities/utilities#base64Encode(Byte)) is that it seems to default the charset (https://developers.google.com/apps-script/reference/utilities/charset) to US_ASCII unless you explicitly tell it to use UTF_8. Will post update to the Google Web Store with this (and a few other bug fixes).

**Comment by fgweekly** [comment]
You rock. :+1:

**Comment by thiscouldbejd** [comment]
De rien - it's now live on the Web Store!
