### ISSUE TITLE
repositories selector

### ISSUE THREAD

**Issue by Bound3R** [thiscouldbejd/Gabriel#8]
these values could be saved with google account or something.

I would like to only display the list that I want or I can send with this tool to avoid possible errors because with a click all goes to the master branch.

**Comment by thiscouldbejd** [comment]
Hi,

Yes - a customised list of branches/filtered repositories would be a great idea.....will see what I can do next week ;)

Jd

**Comment by Bound3R** [comment]
wow that would be great, attentive thanks, is the only thing that I think he needs urgently :+1:

**Comment by thiscouldbejd** [comment]
Hi Daniel,

Have finished this - added an extra menu item with custom dialog box that allows you to 'untick' the repos that you don't want to see on the sidebar. This is stored in the User-Properties, so they are document independent. All the code is updated in this repo, have tested but want to make triple-sure everything is working before pushing the update to Google. Will pop a message up here when it goes live, should be this evening (UK time) or tomorrow.

JD

**Comment by thiscouldbejd** [comment]
All tested and the update has been speedily approved, so should be live now!

JD
